import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
// import SignInEnforcer from "@/components/signInEnforcer";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const SignInEnforcer = dynamic(() => import("@/components/signInEnforcer"))
  return (
    <html lang="en">
      <body className={" text-black	h-screen  bg-cover"}>
        <SignInEnforcer> {children}</SignInEnforcer>
      </body>
    </html>
  );
}
